version: "3"
services:

  db:
    image: mongo:4.1.3

  back:
    image: kkasai/spring-webflux-demo
    environment:
      - SPRING_DATA_MONGODB_HOST=db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=sample
    ports:
      - "8080:8080"
    depends_on:
      - db

  front:
    image: kkasai/react-demo
    ports:
      - "80:80"
